openapi: 3.0.1
info:
  title: SwiftServe
  description: This is the documentation for the backend API supporting SwiftServe Project.
  contact:
    email: rachitb@gatech.edu
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://swiftserve-dot-thinger.ue.r.appspot.com
  description: Google Cloud temporary URL
tags:
- name: auth
  description: Endpoints related to authentication
- name: group
  description: Endpoints related to group management

paths:
  /auth/register:
    post:
      tags:
      - auth
      summary: Registers a user in the database
      operationId: register
      description: The user must not be already registered in the system. The user must provide at least 8-character password. The user must provide a valid email address. No field can exceed 128 characters.
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/User'
                - $ref: '#/components/schemas/UserLogin'
        required: true
      responses:
        201:
          description: User created successfully
          content: {}
        400:
          description: Invalid email address supplied
          content: {}
        409:
          description: Email address already in use
          content: {}
        422:
          description: Input rules broken - check description
          content: {}
  /auth/login:
    post:
      tags:
      - auth
      summary: Logs in a user
      description: 'Exchanges username and password for a Bearer token. The user must already be registered. The provided combination of email address and password must be correct. No field can exceed 128 characters.'
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
        required: true
      responses:
        200:
          description: User logged in successfully
          content:
            application/json:
              schema:
                properties:
                  access_token:
                    type: string
                    description: JWT access token to be used for future requests
                  token_type:
                    type: string
                    description: Type of the access token - currently, defaults to bearer
        400:
          description: The provided combination of email address and password was invalid
          content: {}
  /group:
    put:
      tags:
        - group
      summary: Creates a group for the user
      operationId: create_group
      description: The user must be registered and logged in to use this endpoint.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
        required: true
      responses:
        200:
          description: Group created successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Group'
                  - $ref: '#/components/schemas/GroupHiddenDetails'
        401:
          description: User unauthorized / Bearer token expired
          content: {}
        422:
          description: Group name already exists
          content: {}
    post:
      tags:
        - group
      summary: Registers a user in a group
      operationId: join_group
      description: The user must be registered and logged in to use this endpoint. The user must not be the owner / host of the group.
      responses:
        200:
          description: Group joined successfully
          content: {}
        401:
          description: User unauthorized / Bearer token expired
          content: {}
        422:
          description: User is the owner of group - owners cannot join their own group
          content: {}
    get:
      tags:
        - group
      summary: Gets a list of groups the user is a part / owner of
      operationId: get_all_groups
      description: The user must be registered and logged in to use this endpoint.
      responses:
        200:
          description: List of groups the user is a part / owner of
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupArray'
        401:
          description: User unauthorized / Bearer token expired
          content: {}

components:
  schemas:
    User:
      type: object
      required:
        - email
      properties:
        id:
          type: string
          description: Internal ID of the user, as seen in the database
          format: int64
        email:
          type: string
          description: Email address of the user
          format: email
          minLength: 3
          maxLength: 128
    UserLogin:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 128
          description: Username, as requested by the user, defaulted to email address
          format: email
        password:
          type: string
          description: Password of the user
          format: password
          minLength: 8
          maxLength: 128
    GroupID:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          description: Internal ID of the group, as seen in the database
          format: int64
    Group:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          description: Internal ID of the group, as seen in the database
          format: int64
        name:
          type: string
          description: Short description of the group
          minLength: 3
          maxLength: 128
    GroupHiddenDetails:
      type: object
      properties:
        creation_time:
          type: string
          description: DateTime of the group's creation time
          format: date-time
        is_active:
          type: boolean
          description: Flag denoting whether or not is a group active
    GroupArray:
      type: object
      required:
        - name
      properties:
        groups:
          type: array
          description: An array of group objects
          items:
            $ref: '#/components/schemas/Group'

  securitySchemes:
    userAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
